enyo.depends(
	"wijcal.js",
    "themes/rocket/jquery-wijmo.css",
    "external/jquery-1.7.1.min.js",
    "external/jquery-ui-1.8.18.custom.min.js",
    "external/globalize.min.js",
    "themes/wijmo/jquery.wijmo.wijcalendar.css",
    "wijmo/jquery.wijmo.wijpopup.js",
    "wijmo/jquery.wijmo.wijcalendar.js"
);